/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnnouncementType = IDL.Variant({
  'market_tip' : IDL.Null,
  'system_notice' : IDL.Null,
  'general' : IDL.Null,
});
export const NewsItem = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'publishedAt' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'announcementType' : AnnouncementType,
  'isPublished' : IDL.Bool,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const UrlPreview = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'tab' : IDL.Text,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'shills' : IDL.Vec(IDL.Principal),
  'fuds' : IDL.Vec(IDL.Principal),
  'authorName' : IDL.Text,
  'likes' : IDL.Vec(IDL.Principal),
  'imageKey' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'replyToId' : IDL.Opt(IDL.Nat),
  'dislikes' : IDL.Vec(IDL.Principal),
  'authorPrincipal' : IDL.Principal,
  'urlPreview' : IDL.Opt(UrlPreview),
});
export const FearGreedResult = IDL.Record({
  'fetchedAt' : IDL.Int,
  'labelText' : IDL.Text,
  'score' : IDL.Nat,
});
export const ExecutionRecord = IDL.Record({
  'id' : IDL.Text,
  'saleValue' : IDL.Float64,
  'executedAt' : IDL.Int,
  'tokensSold' : IDL.Float64,
  'targetPrice' : IDL.Float64,
  'remainingICP' : IDL.Float64,
});
export const ICP24hStats = IDL.Record({
  'low' : IDL.Float64,
  'isStale' : IDL.Bool,
  'fetchedAt' : IDL.Int,
  'high' : IDL.Float64,
});
export const PriceResult = IDL.Record({
  'isStale' : IDL.Bool,
  'fetchedAt' : IDL.Int,
  'source' : IDL.Text,
  'priceUSD' : IDL.Float64,
});
export const PriceResponse = IDL.Variant({
  'ok' : PriceResult,
  'err' : IDL.Text,
});
export const PriceVolumePoint = IDL.Record({
  'volume24h' : IDL.Float64,
  'timestamp' : IDL.Int,
  'priceUSD' : IDL.Float64,
});
export const MarketDataPoint = IDL.Record({
  'volume24h' : IDL.Float64,
  'timestamp' : IDL.Int,
  'fearGreedScore' : IDL.Nat,
  'priceUSD' : IDL.Float64,
});
export const PriceTarget = IDL.Record({
  'id' : IDL.Text,
  'tokensToSell' : IDL.Float64,
  'notifyViaPhone' : IDL.Bool,
  'targetPrice' : IDL.Float64,
  'notifyEmail' : IDL.Opt(IDL.Text),
  'triggered' : IDL.Bool,
  'icpAmount' : IDL.Float64,
  'notifyViaEmail' : IDL.Bool,
});
export const PortfolioRecord = IDL.Record({
  'priceTargets' : IDL.Vec(PriceTarget),
  'investedAmount' : IDL.Float64,
  'icpAmount' : IDL.Float64,
});
export const SocialTrendingResult = IDL.Record({
  'isStale' : IDL.Bool,
  'fetchedAt' : IDL.Int,
  'score' : IDL.Float64,
});
export const UserSettings = IDL.Record({
  'baseCurrency' : IDL.Opt(IDL.Text),
  'theme' : IDL.Opt(IDL.Text),
  'notifyPhone' : IDL.Opt(IDL.Bool),
  'email' : IDL.Opt(IDL.Text),
  'language' : IDL.Opt(IDL.Text),
  'notifyEmail' : IDL.Opt(IDL.Bool),
  'phone' : IDL.Opt(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAndTriggerAlerts' : IDL.Func([IDL.Float64], [], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, AnnouncementType],
      [IDL.Nat],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteChatMessage' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deletePortfolioRecord' : IDL.Func([], [], []),
  'deleteUserSettings' : IDL.Func([], [], []),
  'fetchAndStoreMarketData' : IDL.Func([], [], []),
  'fetchCoinTelegraphItems' : IDL.Func([], [IDL.Vec(NewsItem)], []),
  'fetchDecryptItems' : IDL.Func([], [IDL.Vec(NewsItem)], []),
  'fetchDfinityBlogItems' : IDL.Func([], [IDL.Vec(NewsItem)], []),
  'getAdminICPBalance' : IDL.Func([], [IDL.Text], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getCurrentFearGreed' : IDL.Func([], [IDL.Opt(FearGreedResult)], ['query']),
  'getCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getDonationAddress' : IDL.Func([], [IDL.Text], ['query']),
  'getExecutionHistory' : IDL.Func([], [IDL.Vec(ExecutionRecord)], ['query']),
  'getICP24hStats' : IDL.Func([], [IDL.Opt(ICP24hStats)], []),
  'getICPNews' : IDL.Func([], [IDL.Vec(NewsItem)], []),
  'getICPNewsRaw' : IDL.Func([], [IDL.Vec(NewsItem)], []),
  'getICPPrice' : IDL.Func([], [PriceResponse], []),
  'getICPPriceRaw' : IDL.Func([], [PriceResponse], []),
  'getMarketChart' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PriceVolumePoint)],
      ['query'],
    ),
  'getMarketHistory' : IDL.Func([], [IDL.Vec(MarketDataPoint)], ['query']),
  'getPortfolioRecord' : IDL.Func([], [PortfolioRecord], ['query']),
  'getPublishedAnnouncements' : IDL.Func(
      [],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getSocialTrending' : IDL.Func([], [SocialTrendingResult], []),
  'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postChatMessage' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Opt(UrlPreview)],
      [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
      [],
    ),
  'saveExecutionRecord' : IDL.Func([ExecutionRecord], [], []),
  'savePortfolioRecord' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Vec(PriceTarget)],
      [],
      [],
    ),
  'saveUserSettings' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Bool),
      ],
      [],
      [],
    ),
  'sendTestEmail' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'toggleAnnouncementPublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleChatLike' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
      [],
    ),
  'toggleChatShill' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
      [],
    ),
  'transformAdminBalance' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformBinance24h' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformCoinTelegraphRss' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformDecryptRss' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformDfinityBlog' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformFearGreed' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformMarketChart' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformNewsItems' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformPrice' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformPriceBinance' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformPriceCoinbase' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformSocialStats' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, AnnouncementType],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnnouncementType = IDL.Variant({
    'market_tip' : IDL.Null,
    'system_notice' : IDL.Null,
    'general' : IDL.Null,
  });
  const NewsItem = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'publishedAt' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'announcementType' : AnnouncementType,
    'isPublished' : IDL.Bool,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const UrlPreview = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'tab' : IDL.Text,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'shills' : IDL.Vec(IDL.Principal),
    'fuds' : IDL.Vec(IDL.Principal),
    'authorName' : IDL.Text,
    'likes' : IDL.Vec(IDL.Principal),
    'imageKey' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'replyToId' : IDL.Opt(IDL.Nat),
    'dislikes' : IDL.Vec(IDL.Principal),
    'authorPrincipal' : IDL.Principal,
    'urlPreview' : IDL.Opt(UrlPreview),
  });
  const FearGreedResult = IDL.Record({
    'fetchedAt' : IDL.Int,
    'labelText' : IDL.Text,
    'score' : IDL.Nat,
  });
  const ExecutionRecord = IDL.Record({
    'id' : IDL.Text,
    'saleValue' : IDL.Float64,
    'executedAt' : IDL.Int,
    'tokensSold' : IDL.Float64,
    'targetPrice' : IDL.Float64,
    'remainingICP' : IDL.Float64,
  });
  const ICP24hStats = IDL.Record({
    'low' : IDL.Float64,
    'isStale' : IDL.Bool,
    'fetchedAt' : IDL.Int,
    'high' : IDL.Float64,
  });
  const PriceResult = IDL.Record({
    'isStale' : IDL.Bool,
    'fetchedAt' : IDL.Int,
    'source' : IDL.Text,
    'priceUSD' : IDL.Float64,
  });
  const PriceResponse = IDL.Variant({ 'ok' : PriceResult, 'err' : IDL.Text });
  const PriceVolumePoint = IDL.Record({
    'volume24h' : IDL.Float64,
    'timestamp' : IDL.Int,
    'priceUSD' : IDL.Float64,
  });
  const MarketDataPoint = IDL.Record({
    'volume24h' : IDL.Float64,
    'timestamp' : IDL.Int,
    'fearGreedScore' : IDL.Nat,
    'priceUSD' : IDL.Float64,
  });
  const PriceTarget = IDL.Record({
    'id' : IDL.Text,
    'tokensToSell' : IDL.Float64,
    'notifyViaPhone' : IDL.Bool,
    'targetPrice' : IDL.Float64,
    'notifyEmail' : IDL.Opt(IDL.Text),
    'triggered' : IDL.Bool,
    'icpAmount' : IDL.Float64,
    'notifyViaEmail' : IDL.Bool,
  });
  const PortfolioRecord = IDL.Record({
    'priceTargets' : IDL.Vec(PriceTarget),
    'investedAmount' : IDL.Float64,
    'icpAmount' : IDL.Float64,
  });
  const SocialTrendingResult = IDL.Record({
    'isStale' : IDL.Bool,
    'fetchedAt' : IDL.Int,
    'score' : IDL.Float64,
  });
  const UserSettings = IDL.Record({
    'baseCurrency' : IDL.Opt(IDL.Text),
    'theme' : IDL.Opt(IDL.Text),
    'notifyPhone' : IDL.Opt(IDL.Bool),
    'email' : IDL.Opt(IDL.Text),
    'language' : IDL.Opt(IDL.Text),
    'notifyEmail' : IDL.Opt(IDL.Bool),
    'phone' : IDL.Opt(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAndTriggerAlerts' : IDL.Func([IDL.Float64], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, AnnouncementType],
        [IDL.Nat],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteChatMessage' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deletePortfolioRecord' : IDL.Func([], [], []),
    'deleteUserSettings' : IDL.Func([], [], []),
    'fetchAndStoreMarketData' : IDL.Func([], [], []),
    'fetchCoinTelegraphItems' : IDL.Func([], [IDL.Vec(NewsItem)], []),
    'fetchDecryptItems' : IDL.Func([], [IDL.Vec(NewsItem)], []),
    'fetchDfinityBlogItems' : IDL.Func([], [IDL.Vec(NewsItem)], []),
    'getAdminICPBalance' : IDL.Func([], [IDL.Text], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getCurrentFearGreed' : IDL.Func([], [IDL.Opt(FearGreedResult)], ['query']),
    'getCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getDonationAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getExecutionHistory' : IDL.Func([], [IDL.Vec(ExecutionRecord)], ['query']),
    'getICP24hStats' : IDL.Func([], [IDL.Opt(ICP24hStats)], []),
    'getICPNews' : IDL.Func([], [IDL.Vec(NewsItem)], []),
    'getICPNewsRaw' : IDL.Func([], [IDL.Vec(NewsItem)], []),
    'getICPPrice' : IDL.Func([], [PriceResponse], []),
    'getICPPriceRaw' : IDL.Func([], [PriceResponse], []),
    'getMarketChart' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PriceVolumePoint)],
        ['query'],
      ),
    'getMarketHistory' : IDL.Func([], [IDL.Vec(MarketDataPoint)], ['query']),
    'getPortfolioRecord' : IDL.Func([], [PortfolioRecord], ['query']),
    'getPublishedAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getSocialTrending' : IDL.Func([], [SocialTrendingResult], []),
    'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postChatMessage' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Opt(UrlPreview)],
        [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
        [],
      ),
    'saveExecutionRecord' : IDL.Func([ExecutionRecord], [], []),
    'savePortfolioRecord' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Vec(PriceTarget)],
        [],
        [],
      ),
    'saveUserSettings' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Bool),
        ],
        [],
        [],
      ),
    'sendTestEmail' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'toggleAnnouncementPublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleChatLike' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
        [],
      ),
    'toggleChatShill' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
        [],
      ),
    'transformAdminBalance' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformBinance24h' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformCoinTelegraphRss' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformDecryptRss' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformDfinityBlog' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformFearGreed' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformMarketChart' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformNewsItems' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformPrice' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformPriceBinance' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformPriceCoinbase' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformSocialStats' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, AnnouncementType],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };