/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'announcementType' : AnnouncementType,
  'isPublished' : boolean,
  'body' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export type AnnouncementType = { 'market_tip' : null } |
  { 'system_notice' : null } |
  { 'general' : null };
export interface ExecutionRecord {
  'id' : string,
  'saleValue' : number,
  'executedAt' : bigint,
  'tokensSold' : number,
  'targetPrice' : number,
  'remainingICP' : number,
}
export interface FearGreedResult {
  'fetchedAt' : bigint,
  'labelText' : string,
  'score' : bigint,
}
export interface ICP24hStats {
  'low' : number,
  'isStale' : boolean,
  'fetchedAt' : bigint,
  'high' : number,
}
export interface MarketDataPoint {
  'volume24h' : number,
  'timestamp' : bigint,
  'fearGreedScore' : bigint,
  'priceUSD' : number,
}
export interface NewsItem {
  'url' : string,
  'title' : string,
  'source' : string,
  'publishedAt' : string,
}
export interface PortfolioRecord {
  'priceTargets' : Array<PriceTarget>,
  'investedAmount' : number,
  'icpAmount' : number,
}
export type PriceResponse = { 'ok' : PriceResult } |
  { 'err' : string };
export interface PriceResult {
  'isStale' : boolean,
  'fetchedAt' : bigint,
  'source' : string,
  'priceUSD' : number,
}
export interface PriceTarget {
  'id' : string,
  'tokensToSell' : number,
  'notifyViaPhone' : boolean,
  'targetPrice' : number,
  'notifyEmail' : [] | [string],
  'triggered' : boolean,
  'icpAmount' : number,
  'notifyViaEmail' : boolean,
}
export interface PriceVolumePoint {
  'volume24h' : number,
  'timestamp' : bigint,
  'priceUSD' : number,
}
export interface SocialTrendingResult {
  'isStale' : boolean,
  'fetchedAt' : bigint,
  'score' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'baseCurrency' : [] | [string],
  'theme' : [] | [string],
  'notifyPhone' : [] | [boolean],
  'email' : [] | [string],
  'language' : [] | [string],
  'notifyEmail' : [] | [boolean],
  'phone' : [] | [string],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAndTriggerAlerts' : ActorMethod<[number], undefined>,
  'createAnnouncement' : ActorMethod<
    [string, string, AnnouncementType],
    bigint
  >,
  'deleteAnnouncement' : ActorMethod<[bigint], boolean>,
  'deletePortfolioRecord' : ActorMethod<[], undefined>,
  'deleteUserSettings' : ActorMethod<[], undefined>,
  'fetchAndStoreMarketData' : ActorMethod<[], undefined>,
  'fetchCoinTelegraphItems' : ActorMethod<[], Array<NewsItem>>,
  'fetchDecryptItems' : ActorMethod<[], Array<NewsItem>>,
  'fetchDfinityBlogItems' : ActorMethod<[], Array<NewsItem>>,
  /**
   * / Fetches the ICP balance for the admin wallet address via the ICP Ledger API.
   * / Returns the balance as a Text string (e.g. "1234.5678").
   * / Returns "0.0000" if the HTTP outcall fails or the response cannot be parsed.
   */
  'getAdminICPBalance' : ActorMethod<[], string>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentFearGreed' : ActorMethod<[], [] | [FearGreedResult]>,
  /**
   * / Returns the ICP donation wallet address.
   */
  'getDonationAddress' : ActorMethod<[], string>,
  'getExecutionHistory' : ActorMethod<[], Array<ExecutionRecord>>,
  /**
   * / Returns 24-hour high/low price for ICP. Caches fresh results; returns stale on failure.
   */
  'getICP24hStats' : ActorMethod<[], [] | [ICP24hStats]>,
  /**
   * / Returns recent ICP news items. Each feed is fetched and cached independently
   * / with a 5-minute TTL. Stale cached items are served when a feed fails.
   * / Returns recent ICP news items. Each feed is fetched and cached independently
   * / with a 5-minute TTL. All three feeds are fetched IN PARALLEL so one slow
   * / feed cannot block the others. Stale cached items are served when a feed fails.
   */
  'getICPNews' : ActorMethod<[], Array<NewsItem>>,
  'getICPNewsRaw' : ActorMethod<[], Array<NewsItem>>,
  /**
   * / Fetches the current ICP price, caches successes, and falls back to stale cache.
   * / Returns #ok with isStale=false on a live price, isStale=true for a cached stale
   * / price, or #err only when all sources fail and no cache is available.
   */
  'getICPPrice' : ActorMethod<[], PriceResponse>,
  /**
   * / Transform callback for admin ICP balance HTTP responses.
   */
  'getICPPriceRaw' : ActorMethod<[], PriceResponse>,
  'getMarketChart' : ActorMethod<[bigint], Array<PriceVolumePoint>>,
  'getMarketHistory' : ActorMethod<[], Array<MarketDataPoint>>,
  'getPortfolioRecord' : ActorMethod<[], PortfolioRecord>,
  'getPublishedAnnouncements' : ActorMethod<[], Array<Announcement>>,
  /**
   * / Returns the ICP social trending score (0-100). Caches result; returns stale on failure.
   */
  'getSocialTrending' : ActorMethod<[], SocialTrendingResult>,
  'getUserSettings' : ActorMethod<[], UserSettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveExecutionRecord' : ActorMethod<[ExecutionRecord], undefined>,
  'savePortfolioRecord' : ActorMethod<
    [number, number, Array<PriceTarget>],
    undefined
  >,
  'saveUserSettings' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [boolean],
      [] | [boolean],
    ],
    undefined
  >,
  'sendTestEmail' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'toggleAnnouncementPublished' : ActorMethod<[bigint], boolean>,
  /**
   * / Transform callback for admin ICP balance HTTP responses.
   */
  'transformAdminBalance' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformBinance24h' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformCoinTelegraphRss' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformDecryptRss' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformDfinityBlog' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformFearGreed' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformMarketChart' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformNewsItems' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformPrice' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformPriceBinance' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformPriceCoinbase' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  /**
   * / Counter for announcement IDs -- wrapped in a record so it is mutable by reference.
   */
  'transformSocialStats' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  /**
   * / Cached social trending score (survives upgrades via EOP).
   */
  'updateAnnouncement' : ActorMethod<
    [bigint, string, string, AnnouncementType],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];