/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FearGreedResult {
    fetchedAt: bigint;
    labelText: string;
    score: bigint;
}
export interface MarketDataPoint {
    volume24h: number;
    timestamp: bigint;
    fearGreedScore: bigint;
    priceUSD: number;
}
export interface PriceTarget {
    id: string;
    tokensToSell: number;
    notifyViaPhone: boolean;
    targetPrice: number;
    notifyEmail?: string;
    triggered: boolean;
    icpAmount: number;
    notifyViaEmail: boolean;
}
export interface NewsItem {
    url: string;
    title: string;
    source: string;
    publishedAt: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ExecutionRecord {
    id: string;
    saleValue: number;
    executedAt: bigint;
    tokensSold: number;
    targetPrice: number;
    remainingICP: number;
}
export interface PriceResult {
    isStale: boolean;
    fetchedAt: bigint;
    source: string;
    priceUSD: number;
}
export interface UrlPreview {
    url: string;
    title: string;
    thumbnailUrl: string;
    description: string;
}
export type PriceResponse = {
    __kind__: "ok";
    ok: PriceResult;
} | {
    __kind__: "err";
    err: string;
};
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PortfolioRecord {
    priceTargets: Array<PriceTarget>;
    investedAmount: number;
    icpAmount: number;
}
export interface ICP24hStats {
    low: number;
    isStale: boolean;
    fetchedAt: bigint;
    high: number;
}
export interface UserSettings {
    baseCurrency?: string;
    theme?: string;
    notifyPhone?: boolean;
    email?: string;
    language?: string;
    notifyEmail?: boolean;
    phone?: string;
}
export interface ChatMessage {
    id: bigint;
    tab: string;
    isDeleted: boolean;
    content: string;
    shills: Array<Principal>;
    fuds: Array<Principal>;
    authorName: string;
    likes: Array<Principal>;
    imageKey?: string;
    timestamp: bigint;
    replyToId?: bigint;
    dislikes: Array<Principal>;
    authorPrincipal: Principal;
    urlPreview?: UrlPreview;
}
export interface PriceVolumePoint {
    volume24h: number;
    timestamp: bigint;
    priceUSD: number;
}
export interface Announcement {
    id: bigint;
    title: string;
    announcementType: AnnouncementType;
    isPublished: boolean;
    body: string;
    createdAt: bigint;
    updatedAt: bigint;
}
export interface SocialTrendingResult {
    isStale: boolean;
    fetchedAt: bigint;
    score: number;
}
export enum AnnouncementType {
    market_tip = "market_tip",
    system_notice = "system_notice",
    general = "general"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkAndTriggerAlerts(currentPrice: number): Promise<void>;
    createAnnouncement(title: string, body: string, announcementType: AnnouncementType): Promise<bigint>;
    /**
     * / Per-feed news caches (survive upgrades via EOP). Each feed is cached independently
     * / so one failing feed does not evict another feed's previously good items.
     */
    deleteAnnouncement(id: bigint): Promise<boolean>;
    deleteChatMessage(messageId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deletePortfolioRecord(): Promise<void>;
    deleteUserSettings(): Promise<void>;
    fetchAndStoreMarketData(): Promise<void>;
    fetchCoinDeskItems(): Promise<Array<NewsItem>>;
    fetchCoinTelegraphItems(): Promise<Array<NewsItem>>;
    fetchDecryptItems(): Promise<Array<NewsItem>>;
    fetchDfinityBlogItems(): Promise<Array<NewsItem>>;
    /**
     * / Fetches the ICP balance for the admin wallet address via the ICP Ledger API.
     * / Returns the balance as a Text string (e.g. "1234.5678").
     * / Returns "0.0000" if the HTTP outcall fails or the response cannot be parsed.
     */
    getAdminICPBalance(): Promise<string>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getCallerUserRole(): Promise<UserRole>;
    getChatMessages(limit: bigint, offset: bigint): Promise<Array<ChatMessage>>;
    getCurrentFearGreed(): Promise<FearGreedResult | null>;
    /**
     * / Returns the current cycles balance of this canister.
     */
    getCyclesBalance(): Promise<bigint>;
    /**
     * / Returns the ICP donation wallet address.
     */
    getDonationAddress(): Promise<string>;
    getExecutionHistory(): Promise<Array<ExecutionRecord>>;
    /**
     * / Returns 24-hour high/low price for ICP. Caches fresh results; returns stale on failure.
     */
    getICP24hStats(): Promise<ICP24hStats | null>;
    /**
     * / Returns recent ICP news items. Each feed is fetched and cached independently
     * / with a 5-minute TTL. Stale cached items are served when a feed fails.
     * / Returns recent ICP news items. Each feed is fetched and cached independently
     * / with a 5-minute TTL. All three feeds are fetched IN PARALLEL so one slow
     * / feed cannot block the others. Stale cached items are served when a feed fails.
     * / Returns recent ICP news items. Each feed is fetched and cached independently
     * / with a 5-minute TTL. All four feeds are fetched IN PARALLEL so one slow
     * / feed cannot block the others. Stale cached items are served when a feed fails.
     */
    getICPNews(): Promise<Array<NewsItem>>;
    getICPNewsRaw(): Promise<Array<NewsItem>>;
    /**
     * / Fetches the current ICP price, caches successes, and falls back to stale cache.
     * / Returns #ok with isStale=false on a live price, isStale=true for a cached stale
     * / price, or #err only when all sources fail and no cache is available.
     */
    getICPPrice(): Promise<PriceResponse>;
    getICPPriceRaw(): Promise<PriceResponse>;
    getMarketChart(days: bigint): Promise<Array<PriceVolumePoint>>;
    /**
     * / ICP donation address for keeping this service running.
     */
    getMarketHistory(): Promise<Array<MarketDataPoint>>;
    getPortfolioRecord(): Promise<PortfolioRecord>;
    getPublishedAnnouncements(): Promise<Array<Announcement>>;
    /**
     * / Returns the ICP social trending score (0-100). Caches result; returns stale on failure.
     */
    getSocialTrending(): Promise<SocialTrendingResult>;
    /**
     * / Cached 24-hour high/low stats (survives upgrades via EOP).
     */
    getUserSettings(): Promise<UserSettings>;
    isCallerAdmin(): Promise<boolean>;
    postChatMessage(content: string, imageKey: string | null, replyToId: bigint | null, urlPreview: UrlPreview | null): Promise<{
        __kind__: "ok";
        ok: ChatMessage;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveExecutionRecord(record: ExecutionRecord): Promise<void>;
    savePortfolioRecord(icpAmount: number, investedAmount: number, priceTargets: Array<PriceTarget>): Promise<void>;
    /**
     * / Persistent announcements store (keyed by Nat id).
     */
    saveUserSettings(email: string | null, phone: string | null, theme: string | null, baseCurrency: string | null, language: string | null, notifyEmail: boolean | null, notifyPhone: boolean | null): Promise<void>;
    sendTestEmail(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    toggleAnnouncementPublished(id: bigint): Promise<boolean>;
    toggleChatLike(messageId: bigint, isLike: boolean): Promise<{
        __kind__: "ok";
        ok: ChatMessage;
    } | {
        __kind__: "err";
        err: string;
    }>;
    toggleChatShill(messageId: bigint, isShill: boolean): Promise<{
        __kind__: "ok";
        ok: ChatMessage;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Transform callback for admin ICP balance HTTP responses.
     * / Passes through the full response body without truncation.
     */
    transformAdminBalance(input: TransformationInput): Promise<TransformationOutput>;
    transformBinance24h(input: TransformationInput): Promise<TransformationOutput>;
    transformCoinDeskRss(input: TransformationInput): Promise<TransformationOutput>;
    transformCoinTelegraphRss(input: TransformationInput): Promise<TransformationOutput>;
    transformDecryptRss(input: TransformationInput): Promise<TransformationOutput>;
    transformDfinityBlog(input: TransformationInput): Promise<TransformationOutput>;
    transformFearGreed(input: TransformationInput): Promise<TransformationOutput>;
    transformMarketChart(input: TransformationInput): Promise<TransformationOutput>;
    transformNewsItems(input: TransformationInput): Promise<TransformationOutput>;
    transformPrice(input: TransformationInput): Promise<TransformationOutput>;
    transformPriceBinance(input: TransformationInput): Promise<TransformationOutput>;
    transformPriceCoinbase(input: TransformationInput): Promise<TransformationOutput>;
    transformSocialStats(input: TransformationInput): Promise<TransformationOutput>;
    updateAnnouncement(id: bigint, title: string, body: string, announcementType: AnnouncementType): Promise<boolean>;
}
import type { Announcement as _Announcement, AnnouncementType as _AnnouncementType, ChatMessage as _ChatMessage, FearGreedResult as _FearGreedResult, ICP24hStats as _ICP24hStats, PortfolioRecord as _PortfolioRecord, PriceResponse as _PriceResponse, PriceResult as _PriceResult, PriceTarget as _PriceTarget, UrlPreview as _UrlPreview, UserRole as _UserRole, UserSettings as _UserSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkAndTriggerAlerts(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAndTriggerAlerts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAndTriggerAlerts(arg0);
            return result;
        }
    }
    async createAnnouncement(arg0: string, arg1: string, arg2: AnnouncementType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(arg0, arg1, to_candid_AnnouncementType_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(arg0, arg1, to_candid_AnnouncementType_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteAnnouncement(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteChatMessage(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChatMessage(arg0);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChatMessage(arg0);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePortfolioRecord(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePortfolioRecord();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePortfolioRecord();
            return result;
        }
    }
    async deleteUserSettings(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserSettings();
            return result;
        }
    }
    async fetchAndStoreMarketData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAndStoreMarketData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAndStoreMarketData();
            return result;
        }
    }
    async fetchCoinDeskItems(): Promise<Array<NewsItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCoinDeskItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCoinDeskItems();
            return result;
        }
    }
    async fetchCoinTelegraphItems(): Promise<Array<NewsItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCoinTelegraphItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCoinTelegraphItems();
            return result;
        }
    }
    async fetchDecryptItems(): Promise<Array<NewsItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchDecryptItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchDecryptItems();
            return result;
        }
    }
    async fetchDfinityBlogItems(): Promise<Array<NewsItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchDfinityBlogItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchDfinityBlogItems();
            return result;
        }
    }
    async getAdminICPBalance(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminICPBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminICPBalance();
            return result;
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatMessages(arg0: bigint, arg1: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0, arg1);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0, arg1);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentFearGreed(): Promise<FearGreedResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentFearGreed();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentFearGreed();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCyclesBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCyclesBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCyclesBalance();
            return result;
        }
    }
    async getDonationAddress(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationAddress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationAddress();
            return result;
        }
    }
    async getExecutionHistory(): Promise<Array<ExecutionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExecutionHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExecutionHistory();
            return result;
        }
    }
    async getICP24hStats(): Promise<ICP24hStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getICP24hStats();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getICP24hStats();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getICPNews(): Promise<Array<NewsItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getICPNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getICPNews();
            return result;
        }
    }
    async getICPNewsRaw(): Promise<Array<NewsItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getICPNewsRaw();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getICPNewsRaw();
            return result;
        }
    }
    async getICPPrice(): Promise<PriceResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getICPPrice();
                return from_candid_PriceResponse_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getICPPrice();
            return from_candid_PriceResponse_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getICPPriceRaw(): Promise<PriceResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getICPPriceRaw();
                return from_candid_PriceResponse_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getICPPriceRaw();
            return from_candid_PriceResponse_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketChart(arg0: bigint): Promise<Array<PriceVolumePoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketChart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketChart(arg0);
            return result;
        }
    }
    async getMarketHistory(): Promise<Array<MarketDataPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketHistory();
            return result;
        }
    }
    async getPortfolioRecord(): Promise<PortfolioRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioRecord();
                return from_candid_PortfolioRecord_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioRecord();
            return from_candid_PortfolioRecord_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedAnnouncements();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedAnnouncements();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSocialTrending(): Promise<SocialTrendingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getSocialTrending();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSocialTrending();
            return result;
        }
    }
    async getUserSettings(): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return from_candid_UserSettings_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return from_candid_UserSettings_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async postChatMessage(arg0: string, arg1: string | null, arg2: bigint | null, arg3: UrlPreview | null): Promise<{
        __kind__: "ok";
        ok: ChatMessage;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.postChatMessage(arg0, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postChatMessage(arg0, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveExecutionRecord(arg0: ExecutionRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveExecutionRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveExecutionRecord(arg0);
            return result;
        }
    }
    async savePortfolioRecord(arg0: number, arg1: number, arg2: Array<PriceTarget>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePortfolioRecord(arg0, arg1, to_candid_vec_n35(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePortfolioRecord(arg0, arg1, to_candid_vec_n35(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveUserSettings(arg0: string | null, arg1: string | null, arg2: string | null, arg3: string | null, arg4: string | null, arg5: boolean | null, arg6: boolean | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserSettings(to_candid_opt_n31(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserSettings(to_candid_opt_n31(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async sendTestEmail(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendTestEmail();
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendTestEmail();
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleAnnouncementPublished(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAnnouncementPublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAnnouncementPublished(arg0);
            return result;
        }
    }
    async toggleChatLike(arg0: bigint, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: ChatMessage;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleChatLike(arg0, arg1);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleChatLike(arg0, arg1);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleChatShill(arg0: bigint, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: ChatMessage;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleChatShill(arg0, arg1);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleChatShill(arg0, arg1);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async transformAdminBalance(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformAdminBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformAdminBalance(arg0);
            return result;
        }
    }
    async transformBinance24h(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformBinance24h(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformBinance24h(arg0);
            return result;
        }
    }
    async transformCoinDeskRss(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformCoinDeskRss(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformCoinDeskRss(arg0);
            return result;
        }
    }
    async transformCoinTelegraphRss(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformCoinTelegraphRss(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformCoinTelegraphRss(arg0);
            return result;
        }
    }
    async transformDecryptRss(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformDecryptRss(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformDecryptRss(arg0);
            return result;
        }
    }
    async transformDfinityBlog(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformDfinityBlog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformDfinityBlog(arg0);
            return result;
        }
    }
    async transformFearGreed(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformFearGreed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformFearGreed(arg0);
            return result;
        }
    }
    async transformMarketChart(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformMarketChart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformMarketChart(arg0);
            return result;
        }
    }
    async transformNewsItems(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformNewsItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformNewsItems(arg0);
            return result;
        }
    }
    async transformPrice(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformPrice(arg0);
            return result;
        }
    }
    async transformPriceBinance(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformPriceBinance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformPriceBinance(arg0);
            return result;
        }
    }
    async transformPriceCoinbase(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformPriceCoinbase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformPriceCoinbase(arg0);
            return result;
        }
    }
    async transformSocialStats(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformSocialStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformSocialStats(arg0);
            return result;
        }
    }
    async updateAnnouncement(arg0: bigint, arg1: string, arg2: string, arg3: AnnouncementType): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(arg0, arg1, arg2, to_candid_AnnouncementType_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(arg0, arg1, arg2, to_candid_AnnouncementType_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_AnnouncementType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementType): AnnouncementType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Announcement_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Announcement {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessage_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioRecord_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioRecord): PortfolioRecord {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PriceResponse_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceResponse): PriceResponse {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PriceTarget_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceTarget): PriceTarget {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserSettings_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSettings): UserSettings {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UrlPreview]): UrlPreview | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FearGreedResult]): FearGreedResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ICP24hStats]): ICP24hStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tab: string;
    isDeleted: boolean;
    content: string;
    shills: Array<Principal>;
    fuds: Array<Principal>;
    authorName: string;
    likes: Array<Principal>;
    imageKey: [] | [string];
    timestamp: bigint;
    replyToId: [] | [bigint];
    dislikes: Array<Principal>;
    authorPrincipal: Principal;
    urlPreview: [] | [_UrlPreview];
}): {
    id: bigint;
    tab: string;
    isDeleted: boolean;
    content: string;
    shills: Array<Principal>;
    fuds: Array<Principal>;
    authorName: string;
    likes: Array<Principal>;
    imageKey?: string;
    timestamp: bigint;
    replyToId?: bigint;
    dislikes: Array<Principal>;
    authorPrincipal: Principal;
    urlPreview?: UrlPreview;
} {
    return {
        id: value.id,
        tab: value.tab,
        isDeleted: value.isDeleted,
        content: value.content,
        shills: value.shills,
        fuds: value.fuds,
        authorName: value.authorName,
        likes: value.likes,
        imageKey: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.imageKey)),
        timestamp: value.timestamp,
        replyToId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.replyToId)),
        dislikes: value.dislikes,
        authorPrincipal: value.authorPrincipal,
        urlPreview: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.urlPreview))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    priceTargets: Array<_PriceTarget>;
    investedAmount: number;
    icpAmount: number;
}): {
    priceTargets: Array<PriceTarget>;
    investedAmount: number;
    icpAmount: number;
} {
    return {
        priceTargets: from_candid_vec_n25(_uploadFile, _downloadFile, value.priceTargets),
        investedAmount: value.investedAmount,
        icpAmount: value.icpAmount
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    tokensToSell: number;
    notifyViaPhone: boolean;
    targetPrice: number;
    notifyEmail: [] | [string];
    triggered: boolean;
    icpAmount: number;
    notifyViaEmail: boolean;
}): {
    id: string;
    tokensToSell: number;
    notifyViaPhone: boolean;
    targetPrice: number;
    notifyEmail?: string;
    triggered: boolean;
    icpAmount: number;
    notifyViaEmail: boolean;
} {
    return {
        id: value.id,
        tokensToSell: value.tokensToSell,
        notifyViaPhone: value.notifyViaPhone,
        targetPrice: value.targetPrice,
        notifyEmail: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.notifyEmail)),
        triggered: value.triggered,
        icpAmount: value.icpAmount,
        notifyViaEmail: value.notifyViaEmail
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    baseCurrency: [] | [string];
    theme: [] | [string];
    notifyPhone: [] | [boolean];
    email: [] | [string];
    language: [] | [string];
    notifyEmail: [] | [boolean];
    phone: [] | [string];
}): {
    baseCurrency?: string;
    theme?: string;
    notifyPhone?: boolean;
    email?: string;
    language?: string;
    notifyEmail?: boolean;
    phone?: string;
} {
    return {
        baseCurrency: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.baseCurrency)),
        theme: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.theme)),
        notifyPhone: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.notifyPhone)),
        email: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.email)),
        language: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.language)),
        notifyEmail: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.notifyEmail)),
        phone: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    announcementType: _AnnouncementType;
    isPublished: boolean;
    body: string;
    createdAt: bigint;
    updatedAt: bigint;
}): {
    id: bigint;
    title: string;
    announcementType: AnnouncementType;
    isPublished: boolean;
    body: string;
    createdAt: bigint;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        announcementType: from_candid_AnnouncementType_n9(_uploadFile, _downloadFile, value.announcementType),
        isPublished: value.isPublished,
        body: value.body,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    market_tip: null;
} | {
    system_notice: null;
} | {
    general: null;
}): AnnouncementType {
    return "market_tip" in value ? AnnouncementType.market_tip : "system_notice" in value ? AnnouncementType.system_notice : "general" in value ? AnnouncementType.general : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PriceResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PriceResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ChatMessage;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ChatMessage;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ChatMessage_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PriceTarget>): Array<PriceTarget> {
    return value.map((x)=>from_candid_PriceTarget_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Array<Announcement> {
    return value.map((x)=>from_candid_Announcement_n7(_uploadFile, _downloadFile, x));
}
function to_candid_AnnouncementType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementType): _AnnouncementType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PriceTarget_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceTarget): _PriceTarget {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UrlPreview | null): [] | [_UrlPreview] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    tokensToSell: number;
    notifyViaPhone: boolean;
    targetPrice: number;
    notifyEmail?: string;
    triggered: boolean;
    icpAmount: number;
    notifyViaEmail: boolean;
}): {
    id: string;
    tokensToSell: number;
    notifyViaPhone: boolean;
    targetPrice: number;
    notifyEmail: [] | [string];
    triggered: boolean;
    icpAmount: number;
    notifyViaEmail: boolean;
} {
    return {
        id: value.id,
        tokensToSell: value.tokensToSell,
        notifyViaPhone: value.notifyViaPhone,
        targetPrice: value.targetPrice,
        notifyEmail: value.notifyEmail ? candid_some(value.notifyEmail) : candid_none(),
        triggered: value.triggered,
        icpAmount: value.icpAmount,
        notifyViaEmail: value.notifyViaEmail
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementType): {
    market_tip: null;
} | {
    system_notice: null;
} | {
    general: null;
} {
    return value == AnnouncementType.market_tip ? {
        market_tip: null
    } : value == AnnouncementType.system_notice ? {
        system_notice: null
    } : value == AnnouncementType.general ? {
        general: null
    } : value;
}
function to_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PriceTarget>): Array<_PriceTarget> {
    return value.map((x)=>to_candid_PriceTarget_n36(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
